/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class calc extends javax.swing.JFrame {
StringBuilder numOnScreen = new StringBuilder();
private String num1;
private String num2;
private String answerToScreen;
private char arithOperator = '=';
    /**
     * Creates new form calc
     */
    public calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        output_screen = new javax.swing.JTextField();
        b_three5 = new javax.swing.JButton();
        b_three6 = new javax.swing.JButton();
        b_one = new javax.swing.JButton();
        b_two = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        b_three = new javax.swing.JButton();
        b_equals = new javax.swing.JButton();
        b_four = new javax.swing.JButton();
        b_five = new javax.swing.JButton();
        b_six = new javax.swing.JButton();
        B_seven = new javax.swing.JButton();
        b_eight = new javax.swing.JButton();
        b_nine = new javax.swing.JButton();
        b_zero = new javax.swing.JButton();
        b_clear = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        divide = new javax.swing.JButton();

        jButton9.setText("jButton9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b_three5.setText("3");

        b_three6.setText("3");

        b_one.setText("1");
        b_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_oneActionPerformed(evt);
            }
        });

        b_two.setText("2");
        b_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_twoActionPerformed(evt);
            }
        });

        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        b_three.setText("3");
        b_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_threeActionPerformed(evt);
            }
        });

        b_equals.setText("=");
        b_equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_equalsActionPerformed(evt);
            }
        });

        b_four.setText("4");
        b_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_fourActionPerformed(evt);
            }
        });

        b_five.setText("5");
        b_five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_fiveActionPerformed(evt);
            }
        });

        b_six.setText("6");
        b_six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sixActionPerformed(evt);
            }
        });

        B_seven.setText("7");
        B_seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_sevenActionPerformed(evt);
            }
        });

        b_eight.setText("8");
        b_eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_eightActionPerformed(evt);
            }
        });

        b_nine.setText("9");
        b_nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_nineActionPerformed(evt);
            }
        });

        b_zero.setText("0");
        b_zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_zeroActionPerformed(evt);
            }
        });

        b_clear.setText("c");

        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });

        multiply.setText("*");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });

        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(B_seven)
                            .addComponent(b_four)
                            .addComponent(b_zero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_clear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_equals)
                                .addGap(18, 18, 18)
                                .addComponent(divide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b_five)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b_six))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b_eight)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b_nine)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(minus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(multiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(b_one)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_two)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_three)
                        .addGap(18, 18, 18)
                        .addComponent(plus)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(output_screen, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(309, 309, 309)
                    .addComponent(b_three5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(26, 26, 26)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(319, 319, 319)
                    .addComponent(b_three6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(16, 16, 16)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(output_screen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_three)
                    .addComponent(b_two)
                    .addComponent(b_one)
                    .addComponent(plus))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_four)
                    .addComponent(b_five)
                    .addComponent(b_six)
                    .addComponent(minus))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_seven)
                    .addComponent(b_eight)
                    .addComponent(b_nine)
                    .addComponent(multiply))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_clear)
                    .addComponent(b_equals)
                    .addComponent(divide)
                    .addComponent(b_zero))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(b_three5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(204, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(b_three6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(194, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_oneActionPerformed
       numOnScreen.append("1");
       output_screen.setText(numOnScreen.toString());
    }//GEN-LAST:event_b_oneActionPerformed

    private void b_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_twoActionPerformed
          numOnScreen.append("2");
       output_screen.setText(numOnScreen.toString());
    }//GEN-LAST:event_b_twoActionPerformed

    private void b_threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_threeActionPerformed
        numOnScreen.append("3");
       output_screen.setText(numOnScreen.toString());
    }//GEN-LAST:event_b_threeActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
       num1 = numOnScreen.toString();
       numOnScreen.delete(0,numOnScreen.length());//--delete stringbuider object
       output_screen.setText("");//-- set screen to blank
       arithOperator = '+';
    }//GEN-LAST:event_plusActionPerformed

    private void b_equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_equalsActionPerformed
       num2 = numOnScreen.toString();
       double number1 = Double.parseDouble(num1);
       double number2 = Double.parseDouble(num2);
       double ans = 0;
       switch(arithOperator){
           case'+':
               ans = number1 + number2;
               break;
            case'-':
               ans = number1 - number2;
               break;
            case'*':
               ans = number1 * number2;
               break;  
            case'/':
               ans = number1 / number2;
               break;     
       }
     answerToScreen = String.valueOf(ans);
     output_screen.setText(answerToScreen);
    }//GEN-LAST:event_b_equalsActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
          num1 = numOnScreen.toString();
       numOnScreen.delete(0,numOnScreen.length());//--delete stringbuider object
       output_screen.setText("");//-- set screen to blank
       arithOperator = '-';
    }//GEN-LAST:event_minusActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        num1 = numOnScreen.toString();
       numOnScreen.delete(0,numOnScreen.length());//--delete stringbuider object
       output_screen.setText("");//-- set screen to blank
       arithOperator = '*';
    }//GEN-LAST:event_multiplyActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
         num1 = numOnScreen.toString();
       numOnScreen.delete(0,numOnScreen.length());//--delete stringbuider object
       output_screen.setText("");//-- set screen to blank
       arithOperator = '/';
    }//GEN-LAST:event_divideActionPerformed

    private void b_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_fourActionPerformed
        numOnScreen.append("4");
       output_screen.setText(numOnScreen.toString());
    }//GEN-LAST:event_b_fourActionPerformed

    private void b_fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_fiveActionPerformed
         numOnScreen.append("5");
       output_screen.setText(numOnScreen.toString());
    }//GEN-LAST:event_b_fiveActionPerformed

    private void b_sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sixActionPerformed
          numOnScreen.append("6");
       output_screen.setText(numOnScreen.toString());
    }//GEN-LAST:event_b_sixActionPerformed

    private void B_sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_sevenActionPerformed
         numOnScreen.append("7");
       output_screen.setText(numOnScreen.toString());
    }//GEN-LAST:event_B_sevenActionPerformed

    private void b_eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_eightActionPerformed
        numOnScreen.append("8");
       output_screen.setText(numOnScreen.toString());
    }//GEN-LAST:event_b_eightActionPerformed

    private void b_nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_nineActionPerformed
         numOnScreen.append("9");
       output_screen.setText(numOnScreen.toString());
    }//GEN-LAST:event_b_nineActionPerformed

    private void b_zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_zeroActionPerformed
         numOnScreen.append("0");
       output_screen.setText(numOnScreen.toString());
    }//GEN-LAST:event_b_zeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_seven;
    private javax.swing.JButton b_clear;
    private javax.swing.JButton b_eight;
    private javax.swing.JButton b_equals;
    private javax.swing.JButton b_five;
    private javax.swing.JButton b_four;
    private javax.swing.JButton b_nine;
    private javax.swing.JButton b_one;
    private javax.swing.JButton b_six;
    private javax.swing.JButton b_three;
    private javax.swing.JButton b_three5;
    private javax.swing.JButton b_three6;
    private javax.swing.JButton b_two;
    private javax.swing.JButton b_zero;
    private javax.swing.JButton divide;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton minus;
    private javax.swing.JButton multiply;
    private javax.swing.JTextField output_screen;
    private javax.swing.JButton plus;
    // End of variables declaration//GEN-END:variables
}
